<a href="https://colab.research.google.com/github/huybx/AI-learning-week1/blob/main/Day_8_numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import numpy as np
import random
array1 =np.array(list(random.sample(range(2,20),10)))
array2 =np.array(list(random.sample(range(1,10),3)))
array1 =np.vstack((array2, list(random.sample(range(1,10),3))))
array1=np.vstack((array1,list(random.sample(range(1,10),3)))) #np.vstack((list1,list2))

print(array1.shape, array1.ndim, array1.size, array1.dtype)
array2 =np.array(list(random.sample(range(2,20),5)))
print(array2,array2*3, sum(array2))
for i in range(1,4):
  print(array2[-i])

array3=np.zeros((4,4))
print(array3)
for i in range(0,4):
  array3[i][i]=1
print(array3)

(3, 3) 2 9 int64
[ 6  3 17 18  9] [18  9 51 54 27] 53
9
18
17
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
